### ISSUE TITLE
good

### ISSUE THREAD

**Issue by dotnethii** [dmtsys/dmt-meet#7]
please add screen share Desktop and file and chat 
very good

**Comment by davidhq** [comment]
Hi @dotnethii ! Tnx for the compliments. 

Desktop share already works but the icon is not obvious, try the icon with upwards arrow.

Also this app is meant to be self-hosted and better instructions on how to set up are coming.

Chat as well but a bit later.

Demo instance you probably checked could go away soon beause the point is to self-host as described.

thank you again
the team
